### ISSUE TITLE
.co.za not supported?

### ISSUE THREAD

**Issue by vysec** [evilsocket/xray#8]
When using .co.za domain, it thinks za is the TLD and co is the domain...

**Comment by evilsocket** [comment]
I opened an issue on the repo of the library I use for domain parsing, let's wait and hope for a fix, otherwise I'll just implement my own version ;)

**Comment by madaratech** [comment]
yes i noticed this @evilsocket, for eg: if gave input as `-domain test.site.com`  it will scan for `site.com` only and i supposed it will scan for low level subdomain of `test.site.com`, may be the same reason, it's looking for TLD only to scan.

**Comment by madaratech** [comment]
sorry, the above comment is meant for **dnssearch** .

**Comment by evilsocket** [comment]
Well dnssearch is basically the XRAY prototype/poc, they share the same bugs :D

**Comment by madaratech** [comment]
yeah i see XRAY == dnssearch + shodan data for output of dnssearch with UI

**Comment by madaratech** [comment]
@evilsocket you may include **censys.io** data as well for more result may be!

**Comment by evilsocket** [comment]
mmm yeah, plus a more banner grabbers (the info is not from Shodan) ... regarding censys, I can't find anything that Shodan already doesn't give me ... actually, I'll implement a nmap wrapper at some point so people without a Shodan key can use the tool as well.

**Comment by evilsocket** [comment]
Also @madaratech please, don't go off topic, Github Issues != Forum Board

**Comment by evilsocket** [comment]
Fixed:

> Use go get -u github.com/bobesa/go-domain-util/domainutil to update

**Comment by vysec** [comment]
That links dead...

**Comment by evilsocket** [comment]
That's not "a link", but a Go repo, the "go get -u ..." command works fine ;)

**Comment by vysec** [comment]
So I updated, built again and did it again. .co.za still doesn't work hmm.

**Comment by evilsocket** [comment]
did u recompile xray?

**Comment by vysec** [comment]
Yes, so: 
go get -u github.com/bobesa/go-domain-util/domainutil
make get_glide
make install_dependencies
make build

mv build/xray .
./xray .... commands

**Comment by h3ct0rjs** [comment]
same for me @vysec I confirm it.

**Comment by evilsocket** [comment]
It works perfectly fine for me after updating the library and recompiling:

![schermata 2017-07-11 alle 11 44 00](https://user-images.githubusercontent.com/86922/28062457-4b3cdd36-662e-11e7-9eb9-18105e82e1cc.png)

**Comment by h3ct0rjs** [comment]
@evilsocket after testing in another clean enviroment is working...strange. What about @vysec ?

**Comment by evilsocket** [comment]
did you try to rm -rf vendor before make build again?

**Comment by h3ct0rjs** [comment]
Hmmm ok. but as I have mention previously it work in my new devEnviroment, so you can mark this issue as closed. Thanks @evilsocket
